# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f069fdb4faa7e8b3585a8e3948c07102b6943b2cc304f1e4b87a3b515d52ac0230cd17c2b3982764df67905ca552a0adef767553756b95172dd50f19a0d6137b

test:
  secret_key_base: 3273d51b2d0c93bd0a08d42239f157154053acd20c667eaec605549e49c74ce69668b4865fc73fd15927329d8d95518638c4631ea257ba79e9de074689eaf117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
